/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSupplierRouteImport } from './routes/_authed.supplier'
import { Route as AuthedStokOpnameRouteImport } from './routes/_authed.stok-opname'
import { Route as AuthedStokAlertRouteImport } from './routes/_authed.stok-alert'
import { Route as AuthedResepRouteImport } from './routes/_authed.resep'
import { Route as AuthedPortalPelangganRouteImport } from './routes/_authed.portal-pelanggan'
import { Route as AuthedPenggunaRouteImport } from './routes/_authed.pengguna'
import { Route as AuthedPengaturanRouteImport } from './routes/_authed.pengaturan'
import { Route as AuthedPembelianRouteImport } from './routes/_authed.pembelian'
import { Route as AuthedPelangganRouteImport } from './routes/_authed.pelanggan'
import { Route as AuthedObatRouteImport } from './routes/_authed.obat'
import { Route as AuthedNotifikasiRouteImport } from './routes/_authed.notifikasi'
import { Route as AuthedLaporanRouteImport } from './routes/_authed.laporan'
import { Route as AuthedKasirRouteImport } from './routes/_authed.kasir'
import { Route as AuthedInventoriRouteImport } from './routes/_authed.inventori'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAnalitikPelangganRouteImport } from './routes/_authed.analitik-pelanggan'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSupplierRoute = AuthedSupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStokOpnameRoute = AuthedStokOpnameRouteImport.update({
  id: '/stok-opname',
  path: '/stok-opname',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStokAlertRoute = AuthedStokAlertRouteImport.update({
  id: '/stok-alert',
  path: '/stok-alert',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResepRoute = AuthedResepRouteImport.update({
  id: '/resep',
  path: '/resep',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPortalPelangganRoute = AuthedPortalPelangganRouteImport.update({
  id: '/portal-pelanggan',
  path: '/portal-pelanggan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPenggunaRoute = AuthedPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPengaturanRoute = AuthedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPembelianRoute = AuthedPembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPelangganRoute = AuthedPelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedObatRoute = AuthedObatRouteImport.update({
  id: '/obat',
  path: '/obat',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNotifikasiRoute = AuthedNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLaporanRoute = AuthedLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKasirRoute = AuthedKasirRouteImport.update({
  id: '/kasir',
  path: '/kasir',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoriRoute = AuthedInventoriRouteImport.update({
  id: '/inventori',
  path: '/inventori',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalitikPelangganRoute = AuthedAnalitikPelangganRouteImport.update({
  id: '/analitik-pelanggan',
  path: '/analitik-pelanggan',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analitik-pelanggan': typeof AuthedAnalitikPelangganRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inventori': typeof AuthedInventoriRoute
  '/kasir': typeof AuthedKasirRoute
  '/laporan': typeof AuthedLaporanRoute
  '/notifikasi': typeof AuthedNotifikasiRoute
  '/obat': typeof AuthedObatRoute
  '/pelanggan': typeof AuthedPelangganRoute
  '/pembelian': typeof AuthedPembelianRoute
  '/pengaturan': typeof AuthedPengaturanRoute
  '/pengguna': typeof AuthedPenggunaRoute
  '/portal-pelanggan': typeof AuthedPortalPelangganRoute
  '/resep': typeof AuthedResepRoute
  '/stok-alert': typeof AuthedStokAlertRoute
  '/stok-opname': typeof AuthedStokOpnameRoute
  '/supplier': typeof AuthedSupplierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/analitik-pelanggan': typeof AuthedAnalitikPelangganRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/inventori': typeof AuthedInventoriRoute
  '/kasir': typeof AuthedKasirRoute
  '/laporan': typeof AuthedLaporanRoute
  '/notifikasi': typeof AuthedNotifikasiRoute
  '/obat': typeof AuthedObatRoute
  '/pelanggan': typeof AuthedPelangganRoute
  '/pembelian': typeof AuthedPembelianRoute
  '/pengaturan': typeof AuthedPengaturanRoute
  '/pengguna': typeof AuthedPenggunaRoute
  '/portal-pelanggan': typeof AuthedPortalPelangganRoute
  '/resep': typeof AuthedResepRoute
  '/stok-alert': typeof AuthedStokAlertRoute
  '/stok-opname': typeof AuthedStokOpnameRoute
  '/supplier': typeof AuthedSupplierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authed/analitik-pelanggan': typeof AuthedAnalitikPelangganRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/inventori': typeof AuthedInventoriRoute
  '/_authed/kasir': typeof AuthedKasirRoute
  '/_authed/laporan': typeof AuthedLaporanRoute
  '/_authed/notifikasi': typeof AuthedNotifikasiRoute
  '/_authed/obat': typeof AuthedObatRoute
  '/_authed/pelanggan': typeof AuthedPelangganRoute
  '/_authed/pembelian': typeof AuthedPembelianRoute
  '/_authed/pengaturan': typeof AuthedPengaturanRoute
  '/_authed/pengguna': typeof AuthedPenggunaRoute
  '/_authed/portal-pelanggan': typeof AuthedPortalPelangganRoute
  '/_authed/resep': typeof AuthedResepRoute
  '/_authed/stok-alert': typeof AuthedStokAlertRoute
  '/_authed/stok-opname': typeof AuthedStokOpnameRoute
  '/_authed/supplier': typeof AuthedSupplierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/analitik-pelanggan'
    | '/dashboard'
    | '/inventori'
    | '/kasir'
    | '/laporan'
    | '/notifikasi'
    | '/obat'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/pengguna'
    | '/portal-pelanggan'
    | '/resep'
    | '/stok-alert'
    | '/stok-opname'
    | '/supplier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/analitik-pelanggan'
    | '/dashboard'
    | '/inventori'
    | '/kasir'
    | '/laporan'
    | '/notifikasi'
    | '/obat'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/pengguna'
    | '/portal-pelanggan'
    | '/resep'
    | '/stok-alert'
    | '/stok-opname'
    | '/supplier'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/sitemap.xml'
    | '/_authed/analitik-pelanggan'
    | '/_authed/dashboard'
    | '/_authed/inventori'
    | '/_authed/kasir'
    | '/_authed/laporan'
    | '/_authed/notifikasi'
    | '/_authed/obat'
    | '/_authed/pelanggan'
    | '/_authed/pembelian'
    | '/_authed/pengaturan'
    | '/_authed/pengguna'
    | '/_authed/portal-pelanggan'
    | '/_authed/resep'
    | '/_authed/stok-alert'
    | '/_authed/stok-opname'
    | '/_authed/supplier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/supplier': {
      id: '/_authed/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof AuthedSupplierRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stok-opname': {
      id: '/_authed/stok-opname'
      path: '/stok-opname'
      fullPath: '/stok-opname'
      preLoaderRoute: typeof AuthedStokOpnameRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stok-alert': {
      id: '/_authed/stok-alert'
      path: '/stok-alert'
      fullPath: '/stok-alert'
      preLoaderRoute: typeof AuthedStokAlertRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resep': {
      id: '/_authed/resep'
      path: '/resep'
      fullPath: '/resep'
      preLoaderRoute: typeof AuthedResepRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/portal-pelanggan': {
      id: '/_authed/portal-pelanggan'
      path: '/portal-pelanggan'
      fullPath: '/portal-pelanggan'
      preLoaderRoute: typeof AuthedPortalPelangganRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pengguna': {
      id: '/_authed/pengguna'
      path: '/pengguna'
      fullPath: '/pengguna'
      preLoaderRoute: typeof AuthedPenggunaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pengaturan': {
      id: '/_authed/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthedPengaturanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pembelian': {
      id: '/_authed/pembelian'
      path: '/pembelian'
      fullPath: '/pembelian'
      preLoaderRoute: typeof AuthedPembelianRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pelanggan': {
      id: '/_authed/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof AuthedPelangganRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/obat': {
      id: '/_authed/obat'
      path: '/obat'
      fullPath: '/obat'
      preLoaderRoute: typeof AuthedObatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/notifikasi': {
      id: '/_authed/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AuthedNotifikasiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/laporan': {
      id: '/_authed/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthedLaporanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kasir': {
      id: '/_authed/kasir'
      path: '/kasir'
      fullPath: '/kasir'
      preLoaderRoute: typeof AuthedKasirRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventori': {
      id: '/_authed/inventori'
      path: '/inventori'
      fullPath: '/inventori'
      preLoaderRoute: typeof AuthedInventoriRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analitik-pelanggan': {
      id: '/_authed/analitik-pelanggan'
      path: '/analitik-pelanggan'
      fullPath: '/analitik-pelanggan'
      preLoaderRoute: typeof AuthedAnalitikPelangganRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAnalitikPelangganRoute: typeof AuthedAnalitikPelangganRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInventoriRoute: typeof AuthedInventoriRoute
  AuthedKasirRoute: typeof AuthedKasirRoute
  AuthedLaporanRoute: typeof AuthedLaporanRoute
  AuthedNotifikasiRoute: typeof AuthedNotifikasiRoute
  AuthedObatRoute: typeof AuthedObatRoute
  AuthedPelangganRoute: typeof AuthedPelangganRoute
  AuthedPembelianRoute: typeof AuthedPembelianRoute
  AuthedPengaturanRoute: typeof AuthedPengaturanRoute
  AuthedPenggunaRoute: typeof AuthedPenggunaRoute
  AuthedPortalPelangganRoute: typeof AuthedPortalPelangganRoute
  AuthedResepRoute: typeof AuthedResepRoute
  AuthedStokAlertRoute: typeof AuthedStokAlertRoute
  AuthedStokOpnameRoute: typeof AuthedStokOpnameRoute
  AuthedSupplierRoute: typeof AuthedSupplierRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalitikPelangganRoute: AuthedAnalitikPelangganRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInventoriRoute: AuthedInventoriRoute,
  AuthedKasirRoute: AuthedKasirRoute,
  AuthedLaporanRoute: AuthedLaporanRoute,
  AuthedNotifikasiRoute: AuthedNotifikasiRoute,
  AuthedObatRoute: AuthedObatRoute,
  AuthedPelangganRoute: AuthedPelangganRoute,
  AuthedPembelianRoute: AuthedPembelianRoute,
  AuthedPengaturanRoute: AuthedPengaturanRoute,
  AuthedPenggunaRoute: AuthedPenggunaRoute,
  AuthedPortalPelangganRoute: AuthedPortalPelangganRoute,
  AuthedResepRoute: AuthedResepRoute,
  AuthedStokAlertRoute: AuthedStokAlertRoute,
  AuthedStokOpnameRoute: AuthedStokOpnameRoute,
  AuthedSupplierRoute: AuthedSupplierRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
